version: '3.8'

services:
  db:
    image: mysql:8.4 # Cloud SQL과 같은 버전
    container_name: filly-mysql
    restart: always
    environment:
      MYSQL_DATABASE: filly_db       # DB name
      MYSQL_USER: filly_db           # DB Username
      MYSQL_PASSWORD: 1234  # 사용할 비밀번호 (임의 설정)
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql